### ISSUE TITLE
Consider moving to pytest-dev

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/unittest2pytest#1]
What do you say to move this project to the [pytest-dev](https://github.com/pytest-dev) organization? :smile:

The only missing requirement would be to add a `tox.ini` for running the tests in different python versions, but that would be easy to do.

**Comment by htgoebel** [comment]
This would be fine for me. Esp. since this (hopefully) unburdens me from being the single maintainer.

I only want to still be an owner, since the tool is published under my name. I'll happily share ownership, here and at pypi.

I've found these instructions https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization

**Comment by nicoddemus** [comment]
Certainly you would still be the owner of the package, but it would gain more visibility and other pytest developers would be able to contribute as well. Please read [this section](https://github.com/pytest-dev/pytest/blob/master/CONTRIBUTING.rst#id8) in the CONTRIBUTING docs.

To move it, please transfer the ownership to one of the pytest core developers and then you will get added to the pytest-dev team. I'm going out right now and will only be able to come back tomorrow, so in meanwhile maybe @The-compiler or @RonnyPfannschmidt can assist here if you don't want to wait. :smile:

**Comment by htgoebel** [comment]
Done.

I also added the `tox.ini` you requested. Please note that test at the current develop head fail ATM, since this is work in progress.

**Comment by The-Compiler** [comment]
Awesome! So the next step would be to subscribe to the [mailing list](https://mail.python.org/mailman/listinfo/pytest-dev) and write a mail requesting the move, linking to this thread. After that's done, I can take care of moving it.

**Comment by nicoddemus** [comment]
Missed this message Florian, just moved it. :smile:

@htgoebel would you please update links in README and pypi to the new location? You are now a member of pytest-dev and have write access to all repositories, plus you're admin of `pytest-dev/unittest2pytest`. Let me know (or any other pytest core developer) if you have any questions or feel anything is amiss. :smile:
