### ISSUE TITLE
Undefined variable `pattern` when converting self.raisesRegexp

### ISSUE THREAD

**Issue by boralyl** [pytest-dev/unittest2pytest#23]
When running the following to convert asserts:

```bash
unittest2pytest -f self_assert test/test_foo.py
```

I consistently get the following output with the below test:

```bash
     def test_foo(self):
-        with self.assertRaisesRegexp(ValueError, 'Invalid'):
+        with pytest.raises(ValueError) as excinfo:
             raise ValueError('Invalid')
+        assert re.search(pattern, excinfo.value)
```

Notice the variable `pattern` which isn't defined anywhere. This is with unittest2pytest==0.3

Also, it would be nicer if it didn't use `re.search` and just use the match kwarg to raises.  e.g.

```
     def test_foo(self):
-        with self.assertRaisesRegexp(ValueError, 'Invalid'):
+        with pytest.raises(ValueError, match='Invalid'):
             raise ValueError('Invalid')
```

**Comment by nicoddemus** [comment]
Definitely, thanks for the report. We would appreciate a PR if you have the time, otherwise hope someone can tackle this soon. 👍

**Comment by boralyl** [comment]
Sure thing: https://github.com/pytest-dev/unittest2pytest/pull/24
